// language
export const LANGUAGE_CHANGE_LANGUAGE = 'LANGUAGE_CHANGE_LANGUAGE';

// map
export const MAP_CLICK = 'MAP_CLICK';
export const MAP_CHANGE_VALUE = 'MAP_CHANGE_VALUE';

// searchBar
export const SEARCHBAR_SEARCHQUERY_FOCUS = 'SEARCHBAR_SEARCHQUERY_FOCUS';
export const SEARCHBAR_CHANGE_VALUE = 'SEARCHBAR_CHANGE_VALUE';

// tweetsPopup
export const POPUP_CLOSE = 'POPUP_CLOSE';
export const POPUP_CHANGE_VALUE = 'POPUP_CHANGE_VALUE';

// slidePanel
export const SLIDEPANEL_CHANGE_VALUE = 'SLIDEPANEL_CHANGE_VALUE';
export const SLIDEPANEL_HIDE = 'SLIDEPANEL_HIDE';

// tweets
export const TWEETS_REQUEST_TWEETS = 'TWEETS_REQUEST';
export const TWEETS_RECEIVE_TWEETS = 'TWEETS_RECEIVE_TWEETS';

// errors
export const PAGE_ERROR = 'PAGE_ERROR';
export const PAGE_NO_ERROR = 'PAGE_NO_ERROR';
