// map
export const MAP_CLICK = 'MAP_CLICK';
export const MAP_CHANGE_VALUE = 'MAP_CHANGE_VALUE';

// searchBar
export const SEARCHBAR_SEARCHQUERY_FOCUS = 'SEARCHBAR_SEARCHQUERY_FOCUS';
export const SEARCHBAR_CHANGE_VALUE = 'SEARCHBAR_CHANGE_VALUE';

// tweetsPopup
export const POPUP_CLOSE = 'POPUP_CLOSE';
export const POPUP_SHOW = 'POPUP_SHOW';

// tweets
export const TWEETS_SEARCH_FETCHING = 'TWEETS_REQUEST';
export const TWEETS_SEARCH_FINISHED = 'TWEETS_SEARCH_FINISHED';

// errors
export const PAGE_ERROR = 'PAGE_ERROR';
